name: Push documentation on public repository

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Branch di partenza da cui fare checkout'
        required: true
        default: 'docs/from-gitbook'
        type: string
      target_branch:
        description: 'Branch della repo pubblica da cui fare checkout e su cui pushare'
        required: true
        default: 'main'
        type: string
      public_repository:
        description: 'Repository pubblico di destinazione (formato: owner/repo)'
        required: true
        default: 'pagopa/public_doc'
        type: string
      commit_message:
        description: 'Messaggio di commit personalizzato'
        required: false
        default: 'feat: aggiornamento manuale dal repo sorgente'
        type: string

jobs:
  push-to-target:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}
          path: private_repo

      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}
          repository: ${{ inputs.public_repository }}
          token: ${{ secrets.PAT }}
          path: public-repo

      - name: Push commit to public repo
        run: |
          cd public-repo
          
          git config user.name ${{ vars.GH_USER_NAME }}
          git config user.email ${{ vars.GH_MAIL }}
          
          # here, add filest to the commit
          
          if git diff-index --quiet HEAD; then
            echo "No updates to commit"
          else
            git commit -m "${{ inputs.commit_message || 'update documentation' }}"
            git push origin ${{ inputs.target_branch }}
          fi